set number
set relativenumber
set nobackup
set noswapfile
set nowritebackup
set mouse=a
set clipboard=unnamed
syntax enable
set showcmd
set encoding=utf-8
set showmatch 
set sw=2
set laststatus=2
set showmatch
set splitright
set foldmethod=indent
set foldlevel=99
set numberwidth=2
set pyxversion=3